# Generated by Django 4.0.5 on 2022-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTiendaShunApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacion',
            name='foto',
            field=models.ImageField(default='WebTiendaShunApp/static/images/no-img.jpg', upload_to='WebTiendaShunApp'),
        ),
    ]
