# Generated by Django 4.0.5 on 2022-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTiendaShunApp', '0004_alter_alimentacion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='foto',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
